### ISSUE TITLE
Error while compiling in release mode

### ISSUE THREAD

**Issue by EnricoTirri** [Dev-hwang/flutter_foreground_task#105]
I'm trying to compile my project using "flutter run --release" command, but android studio gives me these errors
this happens since i've updated to flutter 3.3.0

e: C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_foreground_task-3.8.2\android\src\main\kotlin\com\pravera\flutter_foreground_task\MethodCallHandlerImpl.kt: (18, 7): Redeclaration: MethodCallHandlerImpl
e: C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_foreground_task-3.8.2\android\src\main\kotlin\com\pravera\flutter_foreground_task\models\ForegroundTaskOptions.kt: (6, 12): Redeclaration: ForegroundTaskOptions
e: C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_foreground_task-3.8.2\android\src\main\kotlin\com\pravera\flutter_foreground_task\service\ForegroundService.kt: (40, 7): Redeclaration: ForegroundService
e: C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_foreground_task-3.8.2\android\src\main\kotlin\com\pravera\flutter_foreground_task\service\ForegroundServicePrefsKey.kt: (9, 8): Redeclaration: ForegroundServicePrefsKey
e: C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_foreground_task-3.8.2\android\src\main\kotlin\com\pravera\flutter_foreground_task\utils\ForegroundServiceUtils.kt: (19, 7): Redeclaration: ForegroundServiceUtils
e: C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_foreground_task-3.9.0\android\src\main\kotlin\com\pravera\flutter_foreground_task\MethodCallHandlerImpl.kt: (18, 7): Redeclaration: MethodCallHandlerImpl
e: C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_foreground_task-3.9.0\android\src\main\kotlin\com\pravera\flutter_foreground_task\MethodCallHandlerImpl.kt: (81, 73): Too many arguments for public final fun openSystemAlertWindowSettings(activity: Activity?, requestCode: Int): Unit defined in com.pravera.flutter_foreground_task.utils.ForegroundServiceUtils.Companione: C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_foreground_task-3.9.0\android\src\main\kotlin\com\pravera\flutter_foreground_task\models\ForegroundTaskOptions.kt: (6, 12): Redeclaration: ForegroundTaskOptions
e: C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_foreground_task-3.9.0\android\src\main\kotlin\com\pravera\flutter_foreground_task\models\ForegroundTaskOptions.kt: (21, 59): Unresolved reference: ALLOW_WAKE_LOCK
e: C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_foreground_task-3.9.0\android\src\main\kotlin\com\pravera\flutter_foreground_task\models\ForegroundTaskOptions.kt: (37, 17): Cannot find a parameter with this name: allowWakeLock
e: C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_foreground_task-3.9.0\android\src\main\kotlin\com\pravera\flutter_foreground_task\models\ForegroundTaskOptions.kt: (50, 51): Unresolved reference: ALLOW_WAKE_LOCK
e: C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_foreground_task-3.9.0\android\src\main\kotlin\com\pravera\flutter_foreground_task\models\ForegroundTaskOptions.kt: (57, 37): Unresolved reference: ALLOW_WAKE_LOCK
e: C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_foreground_task-3.9.0\android\src\main\kotlin\com\pravera\flutter_foreground_task\service\ForegroundService.kt: (41, 7): Redeclaration: ForegroundService
e: C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_foreground_task-3.9.0\android\src\main\kotlin\com\pravera\flutter_foreground_task\service\ForegroundService.kt: (261, 29): Unresolved reference: allowWakeLock
e: C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_foreground_task-3.9.0\android\src\main\kotlin\com\pravera\flutter_foreground_task\service\ForegroundServicePrefsKey.kt: (9, 8): Redeclaration: ForegroundServicePrefsKey
e: C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_foreground_task-3.9.0\android\src\main\kotlin\com\pravera\flutter_foreground_task\utils\ForegroundServiceUtils.kt: (19, 7): Redeclaration: ForegroundServiceUtils

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_foreground_task:compileReleaseKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 39s
Running Gradle task 'assembleRelease'...                           40,6s
Exception: Gradle task assembleRelease failed with exit code 1
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:408:9)
<asynchronous suspension>
#2      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:184:5)
<asynchronous suspension>
#3      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:575:7)
<asynchronous suspension>
#4      FlutterDevice.runCold (package:flutter_tools/src/resident_runner.dart:504:33)
<asynchronous suspension>
#5      ColdRunner.run (package:flutter_tools/src/run_cold.dart:57:28)
<asynchronous suspension>
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:706:27)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>

**Comment by Dev-hwang** [comment]
#15 try this

**Comment by Dev-hwang** [comment]
#15 try this

**Comment by EnricoTirri** [comment]
worked fine, thanks
