### ISSUE TITLE
The app crash after start the service by 2 minutes in release mode

### ISSUE THREAD

**Issue by mahmoud-haj-ali** [Dev-hwang/flutter_foreground_task#135]
I am using **flutter_foreground_task: 4.0.1**, in release mode after starting the service by 2 minutes, if the app is on foreground, it crash and close, and if it was on background, it show that my app keep stopping.

**The crash error:**
```

E/AndroidRuntime(16986): FATAL EXCEPTION: main
E/AndroidRuntime(16986): Process: x.xx.xxx, PID: 16986
E/AndroidRuntime(16986): java.lang.NoSuchMethodError: No interface method requestReviewFlow()LO2/i; in class LX2/a; or its super classes (declaration of 'X2.a' appears in /data/app/x.xx.xxx-Nsv2sHL0iGrab_4zI92q2g==/base.apk!classes2.dex)
E/AndroidRuntime(16986): 	at n4.d.d(Unknown Source:20)
E/AndroidRuntime(16986): 	at n4.d.e(Unknown Source:82)
E/AndroidRuntime(16986): 	at n4.d.onMethodCall(Unknown Source:81)
E/AndroidRuntime(16986): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(Unknown Source:17)
E/AndroidRuntime(16986): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(Unknown Source:18)
E/AndroidRuntime(16986): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(Unknown Source:20)
E/AndroidRuntime(16986): 	at io.flutter.embedding.engine.dart.DartMessenger.a(Unknown Source:0)
E/AndroidRuntime(16986): 	at io.flutter.embedding.engine.dart.a.run(Unknown Source:12)
E/AndroidRuntime(16986): 	at android.os.Handler.handleCallback(Handler.java:900)
E/AndroidRuntime(16986): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime(16986): 	at android.os.Looper.loop(Looper.java:219)
E/AndroidRuntime(16986): 	at android.app.ActivityThread.main(ActivityThread.java:8668)
E/AndroidRuntime(16986): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16986): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime(16986): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

```

**flutter doctor:**
```

> 
> [√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.22621.1194], locale ar-SY)
>     • Flutter version 3.3.10 on channel stable at C:\Src\flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 135454af32 (8 weeks ago), 2022-12-15 07:36:55 -0800
>     • Engine revision 3316dd8728
>     • Dart version 2.18.6
>     • DevTools version 2.15.0
> 
> [!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
>     • Android SDK at C:\Users\mahmo\AppData\Local\Android\sdk
>     • Platform android-33, build-tools 33.0.1
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
>     X Android license status unknown.
>       Run `flutter doctor --android-licenses` to accept the SDK licenses.
>       See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
> 
> [√] Visual Studio - develop for Windows (Visual Studio Enterprise 2022 17.3.5)
>     • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Enterprise
>     • Visual Studio Enterprise 2022 version 17.3.32922.545
>     • Windows 10 SDK version 10.0.20348.0
> 
> [√] Android Studio (version 2021.3)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
> 
> [√] VS Code, 64-bit edition (version 1.60.0)
>     • VS Code at C:\Program Files\Microsoft VS Code
>     • Flutter extension version 3.27.0
> 
> [√] Connected device (4 available)
>     • SNE LX2 (mobile)  • 64X0218B07002965 • android-arm64  • Android 10 (API 29)
>     • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.22621.1194]
>     • Chrome (web)      • chrome           • web-javascript • Google Chrome 109.0.5414.120
>     • Edge (web)        • edge             • web-javascript • Microsoft Edge 109.0.1518.78
> 
> [√] HTTP Host Availability
>     • All required HTTP hosts are available

```

**AndroidManifest:**

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="x.xx.xxx">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.REQUEST_COMPANION_RUN_IN_BACKGROUND" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />
    <uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />

    <application
        android:name=".MyApplication"
        android:exported="true"
        android:icon="@drawable/app_icon"
        android:networkSecurityConfig="@xml/network_security_config"
        tools:targetApi="n">
        <activity
            android:name=".MainActivity"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:exported="true"
            android:hardwareAccelerated="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:usesCleartextTraffic="false"
            android:windowSoftInputMode="adjustResize"
            tools:targetApi="m">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
                android:name="io.flutter.embedding.android.NormalTheme"
                android:exported="true"
                android:resource="@style/NormalTheme" />
            <!-- Displays an Android View that continues showing the launch screen
                 Drawable until Flutter paints its first frame, then this splash
                 screen fades out. A splash screen is useful to avoid any visual
                 gap between the end of Android's launch screen and the painting of
                 Flutter's first frame. -->
            <intent-filter android:exported="true">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:exported="true"
            android:value="ca-app-pub-xxx~xxxx" />

        <service
            android:name="com.ryanheise.audioservice.AudioService"
            android:exported="true">
            <intent-filter android:exported="true">
                <action
                    android:name="android.media.browse.MediaBrowserService"
                    android:exported="true" />
            </intent-filter>
        </service>


        <provider
            android:name="androidx.startup.InitializationProvider"
            android:authorities="${applicationId}.androidx-startup"
            android:exported="false"
            tools:node="merge">
            <meta-data
                android:name="androidx.work.WorkManagerInitializer"
                android:value="androidx.startup"
                tools:node="remove" />
        </provider>

        <!-- declare customized Initializer -->
        <provider
            android:name="vn.hunghd.flutterdownloader.FlutterDownloaderInitializer"
            android:authorities="${applicationId}.flutter-downloader-init"
            android:exported="true">
            <!-- changes this number to configure the maximum number of concurrent tasks -->
            <meta-data
                android:name="vn.hunghd.flutterdownloader.MAX_CONCURRENT_TASKS"
                android:value="1" />
        </provider>

        <service
            android:name="dev.fluttercommunity.plus.androidalarmmanager.AlarmService"
            android:exported="true"
            android:permission="android.permission.BIND_JOB_SERVICE" />

        <receiver
            android:name="dev.fluttercommunity.plus.androidalarmmanager.AlarmBroadcastReceiver"
            android:exported="true" />
        <receiver
            android:name="dev.fluttercommunity.plus.androidalarmmanager.RebootBroadcastReceiver"
            android:enabled="false"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>

        <service
            android:name="flutter.overlay.window.flutter_overlay_window.OverlayService"
            android:exported="true" />

        <service
            android:name="com.pravera.flutter_foreground_task.service.ForegroundService"
            android:foregroundServiceType="dataSync"
            android:enabled="true"
            android:exported="true" />

        <!-- ADD THIS "RECEIVER" element -->
        <receiver
            android:name="com.ryanheise.audioservice.MediaButtonReceiver"
            android:exported="true">
            <intent-filter android:exported="true">
                <action
                    android:name="android.intent.action.MEDIA_BUTTON"
                    android:exported="true" />
            </intent-filter>
        </receiver>
        <meta-data
            android:name="com.google.android.geo.API_KEY"
            android:exported="true"
            android:value="xxxxx" />
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:exported="true"
            android:value="2" />
    </application>
</manifest>

```

**Comment by mahmoud-haj-ali** [comment]
The app keep crashing even when the service is not enabled.

**Comment by mahmoud-haj-ali** [comment]
The exception was from another package, in_app_review
