### ISSUE TITLE
Android 13 Unable to start receiver com.pravera.flutter_foreground_task.service.RestartReceiver

### ISSUE THREAD

**Issue by NguyenVanLinh2016** [Dev-hwang/flutter_foreground_task#148]
I have a crash on devices: 
- Samsung Galaxy S21 FE 5G (android 13)
- Samsung Galaxy S20 FE (android 13)
- OPPO CPH2365 (android 13)
all versions android 13

Im using version: 3.7.3 

Thanks a lot.

Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.pravera.flutter_foreground_task.service.RestartReceiver: android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service com.hlsolution.hoishipper/com.pravera.flutter_foreground_task.service.ForegroundService
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4560)
       at android.app.ActivityThread.-$$Nest$mhandleReceiver()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
       at android.os.Handler.dispatchMessage(Han
[crash_session_6461CD9B02610001293E825568F17D3D_DNE_0_v2_stacktrace.txt](https://github.com/Dev-hwang/flutter_foreground_task/files/11479659/crash_session_6461CD9B02610001293E825568F17D3D_DNE_0_v2_stacktrace.txt)
dler.java:106)
       at android.os.Looper.loopOnce(Looper.java:240)
       at android.os.Looper.loop(Looper.java:351)
       at android.app.ActivityThread.main(ActivityThread.java:8380)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by hwj930513** [comment]
Android 12 or higher, there are restrictions on starting a foreground service.

https://developer.android.com/guide/components/foreground-services#background-start-restrictions

Use the function below to solve this problem.
```dart
FlutterForegroundTask.openIgnoreBatteryOptimizationSettings();

// or

// This function requires `android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS` permission.
FlutterForegroundTask.requestIgnoreBatteryOptimization();
```
