### ISSUE TITLE
Crash app in profile/release mode after call "FlutterForegroundTask.launchApp('/')"

### ISSUE THREAD

**Issue by dkozenkov** [Dev-hwang/flutter_foreground_task#171]
If you compile the application in the profile or release mode, then periodically when you click on the notification and call the method 
"FlutterForegroundTask.launchApp('/')" in the corresponding handler (void onNotificationPressed()), an error occurs:

```
E/AndroidRuntime(21564): java.lang.RuntimeException: Unable to start service com.pravera.flutter_foreground_task.service.ForegroundService@f997bf with Intent { cmp=com.test.app/com.pravera.flutter_foreground_task.service.ForegroundService }: java.lang.IllegalArgumentException
E/AndroidRuntime(21564): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5192)
E/AndroidRuntime(21564): 	at android.app.ActivityThread.access$2200(ActivityThread.java:315)
E/AndroidRuntime(21564): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2324)
E/AndroidRuntime(21564): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(21564): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(21564): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(21564): 	at android.app.ActivityThread.main(ActivityThread.java:8751)
E/AndroidRuntime(21564): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21564): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(21564): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
E/AndroidRuntime(21564): Caused by: java.lang.IllegalArgumentException
E/AndroidRuntime(21564): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2442)
E/AndroidRuntime(21564): 	at android.os.Parcel.createException(Parcel.java:2422)
E/AndroidRuntime(21564): 	at android.os.Parcel.readException(Parcel.java:2405)
E/AndroidRuntime(21564): 	at android.os.Parcel.readException(Parcel.java:2347)
E/AndroidRuntime(21564): 	at android.app.INotificationManager$Stub$Proxy.createNotificationChannels(INotificationManager.java:4790)
E/AndroidRuntime(21564): 	at android.app.NotificationManager.createNotificationChannels(NotificationManager.java:1042)
E/AndroidRuntime(21564): 	at android.app.NotificationManager.createNotificationChannel(NotificationManager.java:947)
E/AndroidRuntime(21564): 	at com.pravera.flutter_foreground_task.service.ForegroundService.startForegroundService(ForegroundService.kt:212)
E/AndroidRuntime(21564): 	at com.pravera.flutter_foreground_task.service.ForegroundService.onStartCommand(ForegroundService.kt:100)
E/AndroidRuntime(21564): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5174)
E/AndroidRuntime(21564): 	... 9 more
E/AndroidRuntime(21564): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime(21564): 	at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:44)
E/AndroidRuntime(21564): 	at com.android.server.notification.PreferencesHelper.createNotificationChannel(PreferencesHelper.java:1014)
E/AndroidRuntime(21564): 	at com.android.server.notification.NotificationManagerService$14.createNotificationChannelsImpl(NotificationManagerService.java:4512)
E/AndroidRuntime(21564): 	at com.android.server.notification.NotificationManagerService$14.createNotificationChannels(NotificationManagerService.java:4543)
E/AndroidRuntime(21564): 	at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:1858)
```

**Comment by tuhombroenemigo** [comment]
any solution?

**Comment by hoyo00** [comment]
@dkozenkov @tuhombroenemigo 

You must allow the permission `android.permission.SYSTEM_ALERT_WINDOW` before requesting `FlutterForegroundTask.launchApp`.

```dart
    if (!await FlutterForegroundTask.canDrawOverlays) {
      // This function requires `android.permission.SYSTEM_ALERT_WINDOW` permission.
      await FlutterForegroundTask.openSystemAlertWindowSettings();
    }
```

**Comment by hoyo00** [comment]
Open the `proguard-rules.pro` file and add the following text.

```
-keep class com.pravera.flutter_foreground_task.** { *; }
```
